name: Anannya, AI Researcher , Writer 
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/


read-time: true
# do you want to show the "tags" inside the posts?
show-tags: true

# Name of your site (displayed in the header)
name: Anannya

# Short bio or description (displayed in the header)
description: Data Enthusiast

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png


theme: jekyll-theme-slate
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: ad18.tk@gmail.com  
  facebook:
  flickr:
  github: Anannya2021
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: -109191120-1


# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://anannya2021.github.io

